./ccs -f test --createcluster ecc_cluster
./ccs -f test --addnode ledhb
./ccs -f test --addmethod 1 ledhb
./ccs -f test --addnode lechb
./ccs -f test --addmethod 1 lechb
./ccs -f test --setcman expected_votes="1" two_node="1"
./ccs -f test --setmulticast 224.0.0.0
./ccs -f test --addfencedev leddrac agent="fence_drac" ipaddr="172.25.0.149" login="root" passwd="#############"
./ccs -f test --addfencedev lecdrac agent="fence_drac" ipaddr="172.25.0.150" login="root" passwd="#############"
./ccs -f test --addfenceinst leddrac ledhb 1
./ccs -f test --addfenceinst lecdrac lechb 1

./ccs -f test --addresource ip address="172.25.0.157" monitor_link="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-led2 " force_fsck="0" force_unmount="1" fsid="19540" fstype="ext3" mountpoint="/usr/sap/LED/SCS00" name="SCS00" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-led1" force_fsck="0" force_unmount="1" fsid="5889" fstype="ext3" mountpoint="/usr/sap/LED/DVEBMGS01" name="DVEBMGS01" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-mnt" force_fsck="0" force_unmount="1" fsid="19541" fstype="ext3" mountpoint="/sapmnt" name="SAPMNT" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-trans" force_fsck="0" force_unmount="1" fsid="56333" fstype="ext3" mountpoint="/usr/sap/trans" name="TRANS" options="rw" self_fence="0"
./ccs -f test --addresource script file="/home/keenable/cifailover" name="CI"
./ccs -f test --addresource ip address="172.25.0.66" monitor_link="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-102" force_fsck="0" force_unmount="1" fsid="12742" fstype="ext3" mountpoint="/oracle/LED/102_64" name="102" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-bkup" force_fsck="0" force_unmount="1" fsid="62800" fstype="ext3" mountpoint="/oracle/LED/sapbackup" name="SAPBACKUP" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-chk" force_fsck="0" force_unmount="1" fsid="50376" fstype="ext3" mountpoint="/oracle/LED/sapcheck" name="SAPCHECK" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-data1" force_fsck="0" force_unmount="1" fsid="25781" fstype="ext3" mountpoint="/oracle/LED/sapdata1" name="SAPDATA1" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-data2" force_fsck="0" force_unmount="1" fsid="13583" fstype="ext3" mountpoint="/oracle/LED/sapdata2" name="SAPDATA2" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-data3" force_fsck="0" force_unmount="1" fsid="1433" fstype="ext3" mountpoint="/oracle/LED/sapdata3" name="SAPDATA3" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-data4" force_fsck="0" force_unmount="1" fsid="36922" fstype="ext3" mountpoint="/oracle/LED/sapdata4" name="SAPDATA4" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-mloga" force_fsck="0" force_unmount="1" fsid="34836" fstype="ext3" mountpoint="/oracle/LED/mirrlogA" name="MIRRLOGA" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-mlogb" force_fsck="0" force_unmount="1" fsid="55726" fstype="ext3" mountpoint="/oracle/LED/mirrlogB" name="MIRRLOGB" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-ologa" force_fsck="0" force_unmount="1" fsid="44535" fstype="ext3" mountpoint="/oracle/LED/origlogA" name="ORIGLOGA" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-ologb" force_fsck="0" force_unmount="1" fsid="64589" fstype="ext3" mountpoint="/oracle/LED/origlogB" name="ORIGLOGB" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-reorg" force_fsck="0" force_unmount="1" fsid="18634" fstype="ext3" mountpoint="/oracle/LED/sapreorg" name="SAPREORG" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-stage" force_fsck="0" force_unmount="1" fsid="20953" fstype="ext3" mountpoint="/oracle/stage/102_64" name="STAGE" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/ora_data-trace" force_fsck="0" force_unmount="1" fsid="48506" fstype="ext3" mountpoint="/oracle/LED/saptrace" name="SAPTRACE" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/arch-oarch" force_fsck="0" force_unmount="1" fsid="38227" fstype="ext3" mountpoint="/oracle/LED/oraarch" name="ORARCH" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/arch-sarch" force_fsck="0" force_unmount="1" fsid="10932" fstype="ext3" mountpoint="/oracle/LED/saparch" name="SAPARCH" options="rw" self_fence="0"
./ccs -f test --addresource script file="/home/keenable/dbfailover" name="DB"
./ccs -f test --addresource fs device="/dev/mapper/data5-sapdata5" force_fsck="0" force_unmount="1" fsid="41132" fstype="ext3" mountpoint="/oracle/LED/sapdata5" name="SAPDATA5" options="rw" self_fence="0"
./ccs -f test --addresource script file="/home/keenable/nfsfailover" name="nfsoffer"
./ccs -f test --addresource fs device="/dev/VolGroup_ID_emcpowerd/sapdata6" force_fsck="0" force_unmount="1" fsid="61718" fstype="ext3" mountpoint="/oracle/LED/sapdata6" name="SAPDATA6" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/VolGroup_ID_emcpowere/sapdata7" force_fsck="0" force_unmount="1" fsid="49536" fstype="ext3" mountpoint="/oracle/LED/sapdata7" name="SAPDATA7" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/VolGroup_ID_emcpowere-Idocarchive" force_fsck="0" force_unmount="1" fsid="43581" fstype="ext3" mountpoint="/Idocarchive" name="IDoc" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/VolGroup_ID_emcpoweri-sapdata8" force_fsck="0" force_unmount="1" fsid="56337" fstype="ext3" mountpoint="/oracle/LED/sapdata8" name="SAPDATA8" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/VolGroup_ID_emcpowerj-sapdata9" force_fsck="0" force_unmount="1" fsid="60551" fstype="ext3" mountpoint="/oracle/LED/sapdata9" name="SAPDATA9" options="rw" self_fence="0"
./ccs -f test --addresource fs device="/dev/mapper/VolGroup_ID_emcpowerh-Archive" force_fsck="0" force_unmount="1" fsid="46604" fstype="ext3" mountpoint="/newIdocarchive" name="IDoc1" options="rw" self_fence="0"
./ccs -f test --addservice DB-ecc autostart="0"
./ccs -f test --addsubservice DB-ecc ip ref="172.25.0.66"
./ccs -f test --addsubservice DB-ecc fs ref="102"
./ccs -f test --addsubservice DB-ecc fs ref="SAPBACKUP"
./ccs -f test --addsubservice DB-ecc fs ref="SAPCHECK"
./ccs -f test --addsubservice DB-ecc fs ref="SAPDATA1"
./ccs -f test --addsubservice DB-ecc fs ref="SAPDATA2"
./ccs -f test --addsubservice DB-ecc fs ref="SAPDATA3"
./ccs -f test --addsubservice DB-ecc fs ref="SAPDATA4"
./ccs -f test --addsubservice DB-ecc fs ref="MIRRLOGA"
./ccs -f test --addsubservice DB-ecc fs ref="MIRRLOGB"
./ccs -f test --addsubservice DB-ecc fs ref="ORIGLOGA"
./ccs -f test --addsubservice DB-ecc fs ref="ORIGLOGB"
./ccs -f test --addsubservice DB-ecc fs ref="SAPREORG"
./ccs -f test --addsubservice DB-ecc fs ref="STAGE"
./ccs -f test --addsubservice DB-ecc fs ref="SAPTRACE"
./ccs -f test --addsubservice DB-ecc fs ref="ORARCH"
./ccs -f test --addsubservice DB-ecc fs ref="SAPARCH"
./ccs -f test --addsubservice DB-ecc fs ref="SAPDATA5"
./ccs -f test --addsubservice DB-ecc fs ref="SAPDATA6"
./ccs -f test --addsubservice DB-ecc fs ref="SAPDATA7"
./ccs -f test --addsubservice DB-ecc fs ref="SAPDATA8"
./ccs -f test --addsubservice DB-ecc fs ref="SAPDATA9"
./ccs -f test --addsubservice DB-ecc script ref="DB"

./ccs -f test --addservice CIApp autostart="0"

./ccs -f test --addsubservice CIApp ip ref="172.25.0.157"
./ccs -f test --addsubservice CIApp fs ref="SCS00"
./ccs -f test --addsubservice CIApp fs ref="DVEBMGS01"
./ccs -f test --addsubservice CIApp fs ref="SAPMNT"
./ccs -f test --addsubservice CIApp fs ref="TRANS"
./ccs -f test --addsubservice CIApp script ref="nfsoffer"
./ccs -f test --addsubservice CIApp fs ref="IDoc"
./ccs -f test --addsubservice CIApp fs ref="IDoc1"
./ccs -f test --addsubservice CIApp script ref="CI"
